arm/urls.py
from django.urls import path
from .views import login_view, logout_view, signup

#동적 URL 생성을 위한 요소
app_name = "users"

urlpatterns = [
    path("logout/", logout_view, name = "logout"),
    path("signup/", signup, name = "signup"),
    path("login/", login_view, name = "login")
]

highlight/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import index

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", index),
    path("users/",include("arm.urls")), # arm 앱의 urls의 것들을 모두 가져온다. 그리고 가져올때 기본적으로 users/가 먼저 온다.
    path("posts/", include("posts.urls"))
]

urlpatterns += static(
    prefix=settings.MEDIA_URL,
    document_root=settings.MEDIA_ROOT
)

posts/urls.py
from django.urls import path
from .views import feeds, comment_add, comment_delete, post_add, tags

#동적URL -> 복잡해질 수록 URL관리가 안되기에 제작
app_name = "posts"

urlpatterns = [
    path("feeds/", feeds, name = "feeds"),
    path("comment_add/", comment_add, name = "comment_add"),
    # views에서 comment = Comment.obejcts.get(id = comment_id)
    # 이렇게 받아주기 때문에 comment_id를 사용하는 것이다.
    path("comment_delete/<int:comment_id>/",comment_delete, name = "comment_delete"),
    path("post_add/", post_add, name = "post_add"),
    path("tags/<str:tag_name>/", tags, name = "tags")
]

posts/models.py
from django.db import models


# Create your models here.
class Post(models.Model):
    user = models.ForeignKey(
        "arm.User", # users가 아니라 arm일 수도 있을것 같다. 어디의 users일까? models안의 파라미터일까?
        # 앱.그 앱의 models에 정의 되어있는 클래스
        verbose_name= "작성자",
        on_delete=models.CASCADE,
    )
    content = models.TextField("내용")
    created = models.DateTimeField("생성일시", auto_now_add=True)
    tags = models.ManyToManyField("posts.HashTag", verbose_name="해시태그 목록", blank=True)
    
    def __str__(self):
        return self.content[:20]
    
class PostImage(models.Model):
    post = models.ForeignKey(
        Post,
        verbose_name="포스트",
        on_delete=models.CASCADE
    )    
    photo = models.ImageField("사진", upload_to="post")

class Comment(models.Model):
    user = models.ForeignKey(
        "arm.User",
        verbose_name="작성자",
        on_delete=models.CASCADE
    )
    post = models.ForeignKey(Post, verbose_name="포스트", on_delete=models.CASCADE)
    content = models.TextField("내용")
    created = models.DateTimeField("생성일시",auto_now_add=True)
    
class HashTag(models.Model):
    name = models.CharField("태그명", max_length=50)
    
    def __str__(self):
        return self.name

posts/forms.py
from django import forms
from .models import Comment, Post

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = [
            "post",
            "content",
            ]
        
        widgets = {
            "content": forms.Textarea(
                attrs = {
                    "placeholder": "댓글달기"
                }
            )
        }
        
class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = [
            "content"
        ]

posts/views.py
from django.shortcuts import render, redirect
from django.views.decorators.http import require_POST
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect, HttpResponseForbidden
from django.urls import reverse

from .models import Post, Comment, PostImage, HashTag
from .forms import CommentForm, PostForm

# Create your views here.
def feeds(request):
    user = request.user
    is_authenticated = user.is_authenticated
    
    if not user.is_authenticated:
        return redirect("/users/login2/")
    
    print("user:", user) # user는 현재 로그인 중인 계정
    print("is_authenticated:", is_authenticated) # 위에서 설정된 is_authenticated로 인해서 해당 user가 정상접근인지 확인,
    # 만약 로그인 되어있지 않으면 False가 나온다.
    
    # 모든 글 목록을 템플릿으로 전달
    posts = Post.objects.all()
    comment_form = CommentForm()
    context = {
        "posts":posts,
        "comment_form": comment_form
        }
    return render(request, "posts/feeds.html", context)

@require_POST
@login_required(login_url="/users/login/")
def comment_add(request):
    #Commment 인스턴스 생성
    form = CommentForm(data = request.POST)
    if form.is_valid():
        # 메모리 상에 Comment 객체 생성
        comment = form.save(commit = False)
        
        #Comment 생성에 필요한 사용자 정보를 request에서 가져와 할당
        # 사용유저 자동입력기능
        comment.user = request.user

        # DB에 Comment 객체 저장
        comment.save()
        
        # 생성된 Comment 정보 확인
        print(comment.id)
        print(comment.content)
        print(comment.user)
        
        # 동적 URL 처리 전
        # return HttpResponseRedirect(f"/posts/feeds/#post-{comment.post.id}")
        # 동적 URL 처리 후
        url = reverse("posts:feeds") + f"#post-{comment.post.id}"
        return HttpResponseRedirect(url)
    
@require_POST
def comment_delete(request, comment_id):
    if request.method == "POST":
        comment = Comment.objects.get(id = comment_id)
        if comment.user == request.user:
            comment.delete()
            # 동적 URL 처리 전
            # return HttpResponseRedirect(f"/posts/feeds/#post-{comment.post.id}")
            # 동적 URL 처리 후
            url = reverse("posts:feeds") + f"#post-{comment.post.id}"
            return HttpResponseRedirect(url)
        else:
            return HttpResponseForbidden("이 댓글을 삭제할 권한이 없습니다.")
        
def post_add(request):
    if request.method == "POST":
        form = PostForm(request.POST)
        
        if form.is_valid():
            post = form.save(commit=False)
            post.user = request.user
            post.save()
            
            for image_file in request.FILES.getlist("images"):
                # request.FILES로 가져온 파일은 models의 ImageField 부분에 바로 할당됨
                PostImage.objects.create(
                    post = post,
                    photo = image_file
                )
                
            tag_string = request.POST.get("tags")
            if tag_string:
                tag_names = [tag_name.strip() for tag_name in tag_string.split(",")]
                for tag_name in tag_names:
                    tag, _ = HashTag.objects.get_or_create(name = tag_name)
                    post.tags.add(tag)
            # 동적 URL 처리 전
            # 모든 PostImage와 Post 생성이 완료되면
            # 피드 페이지로 이동하여 생성된 Post의 위치로 스크롤
            # url = f"/posts/feeds/#post-{post.id}"
            # return HttpResponseRedirect(url)
            # 동적 URL 처리 후
            url = reverse("posts:feeds") + f"#post-{post.id}"
            return HttpResponseRedirect(url)
    # GET 요청일때는 빈 form을 보여준다.
    else:
        form = PostForm()
    context = {"form":form}
    return render(request, "posts/post_add.html", context)
    
def tags(request, tag_name):
    try:
        tag = HashTag.objects.get(name = tag_name)
    except HashTag.DoesNotExist:
        # tag_name에 해당 하는 HashTag를 찾지 못한 경우, 빈 쿼리셋을 리턴
        posts = Post.objects.none()
    else:
        posts = Post.objects.filter(tags = tag)
    
    context = {
        'tag_name': tag_name,
        "posts":posts
    }
    return render(request, "posts/tags.html", context)

templates/posts/feeds.html
{% extends "base.html" %}
{% block content %}
    <nav>
        <h1>
            <a href="{% url 'posts:feeds' %}">햄스터</a>
        </h1>
        <a href="{% url 'posts:post_add' %}">Add Post</a>
        <a href="{% url 'users:logout' %}">Logout</a>
    </nav>
    <div id="feeds" class="post-container">
        {% for post in posts %}
            <article id="post-{{post.id}}" class="post">
                <header class="post-header">
                    {% if post.user.profile_image %}
                        <img src="{{post.user.profile_image.url}}" alt="">
                    {% endif %}
                    <span>{{post.user.username}} </span>
                </header>

                {% comment %} 이미지 슬라이드 시작 {% endcomment %}
                <div class="post-images splide">
                    <div class="splide__track">
                        <ul class="splide__list">
                            {% for image in post.postimage_set.all %}
                                {% if image.photo %}
                                    <li class="splide__slide">
                                        <img src="{{image.photo.url}}" alt="">
                                    </li>
                                {% endif %}
                            {% endfor %}
                        </ul>
                    </div>
                </div>
                <!-- 이미지 슬라이드 마무리 -->
                <!-- 글 내용 출력 시작-->
                <div class="post-content">
                    {{post.content|linebreaksbr}}
                    <div class="post-tags">
                        {% for tag in post.tags.all %}
                            <a href="{% url 'posts:tags' tag_name=tag.name %}">#{{ tag.name }}</a>
                        {% endfor %}
                    </div>
                </div>
                <!-- 글 내용 출력 마무리 -->
                <!-- 좋아요/댓글 표시 시작-->
                <div class="post-buttons">
                    <span>Comments({{post.comment_set.count}})</span>
                </div>
                <!-- 좋아요/댓글 표시 마무리-->
                <!-- 댓글 시작 -->
                <div class="post-comments">
                    <ul>
                        {% for comment in post.comment_set.all %}
                            <li>
                                <span>{{comment.user.username}} </span>
                                <span>{{comment.content}} </span>

                                <!-- 댓글 삭제 form 추가-->
                                {% if user == comment.user %}
                                    <form action="{% url 'posts:comment_delete' comment_id=comment.id %}" method="post">
                                        {% csrf_token %}
                                        <button type="submit">삭제</button>
                                    </form>
                                {% endif %}
                                <!-- 댓글 삭제 form 삭제-->
                            </li>
                        {% endfor %}
                    </ul>
                </div>
                <!-- 댓글 마무리 -->
                <!-- 작성일자, 댓글 입력 창 시작-->
                <small>{{post.created}} </small>
                <div class="post-comment-create">
                    <form action="{% url 'posts:comment_add' %}" method="post">
                        {% csrf_token %}
                        <input type="hidden" name="post" value="{{post.id}}">
                        <!--{{ comment_form.as_p}} 
                        이것으로 해주게되면, 내가 머물고 있는 A포스팅 외에도 B포스팅등
                        드랍다운으로 선택해 줄 수 있어서 적합하지 않다.-->
                        {{comment_form.content}}
                        <button type="submit">게시</button>
                    </form>
                </div>
                <!-- 작성일자, 댓글 입력 창 마무리-->
            </article>
        {% endfor %}
    </div>
    <script>
        const elms = document.getElementsByClassName('splide')
        for (let i = 0; i < elms.length; i++) {
            new Splide(elms[i]).mount();
        }
    </script>
{% endblock  %}

templates/posts/post_add.html
{% extends "base.html" %}
{% block content %}
    <nav>
        <h1>
            <a href="{% url 'posts:feeds' %}">햄스터</a>
        </h1>
        <a href="{% url 'users:logout' %}">logout</a>
    </nav>
    <div id="post-add">
        <h1>Post 작성</h1>
        <form action="" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <div>
                <label for="id_images">이미지</label>
                <input type="file" id="id_images" name="images" multiple>
            </div>
            {{form.as_p}}
            <div>
                <label for="id_tags">해시태그</label>
                <input type="text" id="id_tags" name="tags" placeholder="쉼표(,)로 구분하여 여러 태그 입력">
            </div>
            <button type="submit">게시</button>
        </form>
    </div>
{% endblock  %}

templates/posts/tags.html
{% extends "base.html" %}
{% block content %}
<nav>
    <h1>
        <a href="{% url 'posts:feeds' %}">햄스터</a>
    </h1>
    <a href="{% url 'posts:post_add' %}">Add post</a>
    <a href="{% url 'users:logout' %}">Logout</a>
</nav>
<div id="tags">
    <header class="tags-header">
        <h2>#{{tag_name}} </h2>
        <div>게시물 {{posts.count}}</div>
    </header>
    <div class="post-grid-container">
        {% for post in posts %}
            <!-- Post에 연결된 PostImage가 있으며, 연결된 첫 번째 PostImage의 Photo가 비어있지 않은 경우-->
            {% if post.postimage_set.first and post.postimage_set.first.photo %}
                <div class="post-grid">
                    <img src="{{post.postimage_set.first.photo.url}}" alt="">
                </div>
            {% endif %}
            {% empty %}
                <p>검색된 게시물이 없습니다.</p>
        {% endfor %}
    </div>
</div>
{% endblock content %}